### ISSUE TITLE
Release a release for 0.11

### ISSUE THREAD

**Issue by mmoll** [mavimo/phpstan-junit#16]
Subject says it all. ;)

**Comment by mavimo** [comment]
@mmoll thx for reminder 👍

**Comment by mavimo** [comment]
@mmoll 0.2.0 released, let me know if we can close this issue 😄

**Comment by mmoll** [comment]
@mavimo Working all fine as expected, thanks! :tada:

**Comment by mavimo** [comment]
Great, @mmoll thx for the feedback! 🎉
