### ISSUE TITLE
Support PHPStan 0.12

### ISSUE THREAD

**Issue by ghost** [mavimo/phpstan-junit#34]
PHPStan 0.12 has been released some days ago. It would be great if support could be added for it. Some BC breaks for extension developers are listed [here](https://github.com/phpstan/phpstan/releases/tag/0.12.0). It is possible some of these don't apply to this one.

**Comment by ghost** [comment]
I see dependabot already made a pull request for this in PR #32.

**Comment by mavimo** [comment]
@tominventisbe I'm working on it just now, I'll keep you updated :)

**Comment by mavimo** [comment]
@tominventisbe should be fixed in https://github.com/mavimo/phpstan-junit/pull/35 (I'm going to update docs and release ASAP, let me know if you have some issue, thx!)

**Comment by mavimo** [comment]
@tominventisbe 0.3.0 is now available :)
