### ISSUE TITLE
New feature required?

### ISSUE THREAD

**Issue by mavimo** [mavimo/phpstan-junit#44]
Hi all,

 - [@henrikarordina](https://github.com/henrikarordina/phpstan-junit)
 - [@xyng](https://github.com/interweberde/phpstan-junit)
 - [@majorjackeh](https://github.com/majorjackeh/phpstan-junit)
 - [@moenth](https://github.com/moenth/phpstan-junit)
 - [@mr-feek](https://github.com/mr-feek/phpstan-junit)
 - [@PatrickRombouts](https://github.com/PatrickRombouts/phpstan-junit)
 - [@tominventisbe](https://github.com/tominventisbe/phpstan-junit)
 - [@samcday](https://github.com/samcday/phpstan-junit)
 - [@rquadling](https://github.com/rquadling/phpstan-junit)

I see that you have forked the current project, can I ask if there is something that you can consider to move upstream since is missing from in the current implementation? If you're not considering to move it into upstream can I ask you what's blocking to do that?

Let me know if I can help you to move what you need in the current project!

Cheers
    Marco

**Comment by ghost** [comment]
Thanks for pinging me and caring!

I had forked to develop ffced94551e96435a32800e6b36355d300dbc1d9, which has already been upstreamed, and haven't needed the fork since, as I'm using the upstream package (this one) in all my projects.

EDIT: I deleted my now obsolete fork repository.

**Comment by mavimo** [comment]
@tominventisbe ok, so no actions needed here 👍 

PS: thx to spent some time to reply!
