### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by magikid** [mavimo/phpstan-junit#53]
Do you have any plans to support PHP 8?

**Comment by mavimo** [comment]
@magikid this project should be deprecated, the JUnit support is now in the vanilla phpstan :) 

Take a look to:
 - https://github.com/phpstan/phpstan-src/pull/65

If there is some reason that will force you to use this package LMK and I'll try to improve the official formatter or update this package

**Comment by magikid** [comment]
Cool!  I didn't realize it was built into phpstan now.  Thank you!  I'll close this issue and associated PR.

**Comment by JoshuaBehrens** [comment]
This info could be part of the readme :) I was just scanning all the forks for a compatible one for an update
